#include "../include/attacks.h"
#include <cstring>

namespace Attacks {

// ─── Table storage ────────────────────────────────────────────────────────

Bitboard pawn_attacks[COLOR_NB][SQUARE_NB];
Bitboard knight_attacks[SQUARE_NB];
Bitboard king_attacks[SQUARE_NB];

Bitboard bishop_attacks[SQUARE_NB][512];
Bitboard rook_attacks[SQUARE_NB][4096];
Bitboard bishop_masks[SQUARE_NB];
Bitboard rook_masks[SQUARE_NB];

// Verified magic numbers (generated by magic-finder using our own mask/shift/sq ordering)
uint64_t rook_magics[SQUARE_NB] = {
    0x0280008420400018ULL, 0x0280200080400010ULL, 0x4100081420010040ULL, 0x8200104008200600ULL,
    0x1080040002080081ULL, 0x2880010200800400ULL, 0x8280010000800200ULL, 0x5980002100004080ULL,
    0x2008800c81400121ULL, 0x8000808040002000ULL, 0x0084802000841000ULL, 0x0012001046000820ULL,
    0x0023002431000800ULL, 0x0044010860040050ULL, 0x0085000100040200ULL, 0x001c800041001080ULL,
    0x0120008080004000ULL, 0x2c00808020004000ULL, 0x0800820012260140ULL, 0x1010010010090021ULL,
    0x4202020008041020ULL, 0xa800808004000200ULL, 0x0000040038011210ULL, 0x2001020004008041ULL,
    0x0001400480048122ULL, 0x0000200080400080ULL, 0x0140124500200300ULL, 0x2410004040080401ULL,
    0xc920040080800800ULL, 0x00c0040080800200ULL, 0x0405002100520004ULL, 0x0002010600048044ULL,
    0x0010e14000800882ULL, 0x0010002000400058ULL, 0x02168a1000802000ULL, 0x1301001003002048ULL,
    0x0808000a80800400ULL, 0x0082000400808002ULL, 0x0405280214005001ULL, 0x0302008402000041ULL,
    0x0000800040008020ULL, 0x0480500020004000ULL, 0x1409001020010043ULL, 0x0000104200220008ULL,
    0x52020120040a0010ULL, 0x0200020004008080ULL, 0x0408020001008080ULL, 0x02802a81114a000cULL,
    0x08512b0080024100ULL, 0x2040910020400100ULL, 0x0203806001d00480ULL, 0x020900e0d0000900ULL,
    0x0028080080040080ULL, 0x8000020080040080ULL, 0x1040100108020400ULL, 0x80d1210400844600ULL,
    0x0047012013800445ULL, 0x0020802040001101ULL, 0x0020001100244009ULL, 0x80004500a1100009ULL,
    0x0402002010840882ULL, 0xe052004804013082ULL, 0x00020c8810021b0cULL, 0x1000030144241082ULL
};

uint64_t bishop_magics[SQUARE_NB] = {
    0x000c9004ca040040ULL, 0x1008024082020028ULL, 0x0010010204240401ULL, 0x4014240080808584ULL,
    0x0011104000040054ULL, 0x058c2208c0011000ULL, 0x1080845008040600ULL, 0x0000202210042009ULL,
    0xc0c01320020c8200ULL, 0x0201024801010201ULL, 0x0004041800851908ULL, 0x4000040408900000ULL,
    0x0010011040400000ULL, 0x3271011002112a88ULL, 0x2510341104422004ULL, 0x0000010042422054ULL,
    0x04222004200c0510ULL, 0x0224800234180210ULL, 0x4042020404001200ULL, 0x0008048082004000ULL,
    0x0104005610220000ULL, 0x0800808440504000ULL, 0x02060144020a1260ULL, 0x0001011080484204ULL,
    0x5184464020200400ULL, 0x1004200502028404ULL, 0x4844900008002122ULL, 0x4020080001004008ULL,
    0x1000840088802000ULL, 0x0010008101105004ULL, 0x0200810000880800ULL, 0x1b25090832004100ULL,
    0x4202a02000042880ULL, 0x0010d42051100200ULL, 0x4000108209100400ULL, 0x2100400820420200ULL,
    0x4008022400084100ULL, 0x2022308200410800ULL, 0x409682a200440600ULL, 0x010c010a40202404ULL,
    0x1021440220104013ULL, 0x01088808020148c0ULL, 0x400050c028141000ULL, 0x0460004208020080ULL,
    0x00902010a4010080ULL, 0x6001101000808042ULL, 0x1002100441001098ULL, 0x882400808108020cULL,
    0x40010c0121080499ULL, 0xe006808808420000ULL, 0x8000302108088402ULL, 0x0000280084040890ULL,
    0x4000110810340204ULL, 0xc406900250010404ULL, 0x1040c20882008000ULL, 0x4183080800808800ULL,
    0x200903080a014400ULL, 0x8000020080841084ULL, 0x0402220100824102ULL, 0x010000010820a808ULL,
    0x0002240808102410ULL, 0x020001c090960480ULL, 0xa00060a001820086ULL, 0x0122100906028a08ULL
};

int bishop_shifts[SQUARE_NB];
int rook_shifts[SQUARE_NB];

// ─── Helpers ──────────────────────────────────────────────────────────────

// Generate bishop occupancy mask for a square (excludes edges)
static Bitboard bishop_mask(Square s) {
    Bitboard mask = 0;
    int r, f;
    int sr = rank_of(s), sf = file_of(s);
    for (r = sr+1, f = sf+1; r <= 6 && f <= 6; r++, f++) mask |= square_bb(make_square(f, r));
    for (r = sr+1, f = sf-1; r <= 6 && f >= 1; r++, f--) mask |= square_bb(make_square(f, r));
    for (r = sr-1, f = sf+1; r >= 1 && f <= 6; r--, f++) mask |= square_bb(make_square(f, r));
    for (r = sr-1, f = sf-1; r >= 1 && f >= 1; r--, f--) mask |= square_bb(make_square(f, r));
    return mask;
}

// Generate rook occupancy mask for a square (excludes edges)
static Bitboard rook_mask(Square s) {
    Bitboard mask = 0;
    int sr = rank_of(s), sf = file_of(s);
    for (int r = sr+1; r <= 6; r++) mask |= square_bb(make_square(sf, r));
    for (int r = sr-1; r >= 1; r--) mask |= square_bb(make_square(sf, r));
    for (int f = sf+1; f <= 6; f++) mask |= square_bb(make_square(f, sr));
    for (int f = sf-1; f >= 1; f--) mask |= square_bb(make_square(f, sr));
    return mask;
}

// Classical bishop attack from a square with given occupancy
static Bitboard bishop_attacks_classical(Square s, Bitboard occ) {
    Bitboard atk = 0;
    int sr = rank_of(s), sf = file_of(s);
    int r, f;
    for (r=sr+1,f=sf+1; r<=7&&f<=7; r++,f++) { atk|=square_bb(make_square(f,r)); if(occ&square_bb(make_square(f,r))) break; }
    for (r=sr+1,f=sf-1; r<=7&&f>=0; r++,f--) { atk|=square_bb(make_square(f,r)); if(occ&square_bb(make_square(f,r))) break; }
    for (r=sr-1,f=sf+1; r>=0&&f<=7; r--,f++) { atk|=square_bb(make_square(f,r)); if(occ&square_bb(make_square(f,r))) break; }
    for (r=sr-1,f=sf-1; r>=0&&f>=0; r--,f--) { atk|=square_bb(make_square(f,r)); if(occ&square_bb(make_square(f,r))) break; }
    return atk;
}

// Classical rook attack from a square with given occupancy
static Bitboard rook_attacks_classical(Square s, Bitboard occ) {
    Bitboard atk = 0;
    int sr = rank_of(s), sf = file_of(s);
    for (int r=sr+1; r<=7; r++) { atk|=square_bb(make_square(sf,r)); if(occ&square_bb(make_square(sf,r))) break; }
    for (int r=sr-1; r>=0; r--) { atk|=square_bb(make_square(sf,r)); if(occ&square_bb(make_square(sf,r))) break; }
    for (int f=sf+1; f<=7; f++) { atk|=square_bb(make_square(f,sr)); if(occ&square_bb(make_square(f,sr))) break; }
    for (int f=sf-1; f>=0; f--) { atk|=square_bb(make_square(f,sr)); if(occ&square_bb(make_square(f,sr))) break; }
    return atk;
}

// Enumerate all occupancy subsets of mask (Carry-Rippler) and fill attack
// table using the provided (pre-verified) magic number.
static void init_magic_table(
    Square s,
    Bitboard* attack_table,
    Bitboard mask,
    uint64_t magic,
    int shift,
    bool is_rook)
{
    Bitboard occ = 0;
    do {
        int idx = static_cast<int>((occ * magic) >> shift);
        attack_table[idx] = is_rook ? rook_attacks_classical(s, occ)
                                    : bishop_attacks_classical(s, occ);
        occ = (occ - mask) & mask;
    } while (occ);
}

// ─── init ─────────────────────────────────────────────────────────────────

void init() {
    // ── Pawn attacks ──
    for (int s = 0; s < SQUARE_NB; s++) {
        Bitboard bb = square_bb(Square(s));
        pawn_attacks[WHITE][s] = shift_ne(bb) | shift_nw(bb);
        pawn_attacks[BLACK][s] = shift_se(bb) | shift_sw(bb);
    }

    // ── Knight attacks ──
    for (int s = 0; s < SQUARE_NB; s++) {
        Bitboard bb = square_bb(Square(s));
        Bitboard atk = 0;
        atk |= (bb & NOT_FILE_H) << 17;  // +2 rank, +1 file
        atk |= (bb & NOT_FILE_A) << 15;  // +2 rank, -1 file
        atk |= (bb & NOT_FILE_H & ~FILE_G_BB) << 10; // +1 rank, +2 file
        atk |= (bb & NOT_FILE_A & ~FILE_B_BB) << 6;  // +1 rank, -2 file  -- note: FILE_B reused
        atk |= (bb & NOT_FILE_A) >> 17;
        atk |= (bb & NOT_FILE_H) >> 15;
        atk |= (bb & NOT_FILE_A & ~FILE_B_BB) >> 10; // wait — re-fix
        atk |= (bb & NOT_FILE_H & ~FILE_G_BB) >> 6;
        // Reset and redo correctly
        atk = 0;
        constexpr Bitboard not_AB = ~(FILE_A_BB | FILE_B_BB);
        constexpr Bitboard not_GH = ~(FILE_G_BB | FILE_H_BB);
        atk |= (bb & NOT_FILE_H) << 17;
        atk |= (bb & NOT_FILE_A) << 15;
        atk |= (bb & not_GH)     << 10;
        atk |= (bb & not_AB)     << 6;
        atk |= (bb & NOT_FILE_A) >> 17;
        atk |= (bb & NOT_FILE_H) >> 15;
        atk |= (bb & not_AB)     >> 10;
        atk |= (bb & not_GH)     >> 6;
        knight_attacks[s] = atk;
    }

    // ── King attacks ──
    for (int s = 0; s < SQUARE_NB; s++) {
        Bitboard bb = square_bb(Square(s));
        king_attacks[s] = shift_north(bb) | shift_south(bb) | shift_east(bb) | shift_west(bb)
                         | shift_ne(bb) | shift_nw(bb) | shift_se(bb) | shift_sw(bb);
    }

    // ── Magic bishop/rook tables ──
    for (int s = 0; s < SQUARE_NB; s++) {
        bishop_masks[s]  = bishop_mask(Square(s));
        rook_masks[s]    = rook_mask(Square(s));
        bishop_shifts[s] = 64 - popcount(bishop_masks[s]);
        rook_shifts[s]   = 64 - popcount(rook_masks[s]);

        init_magic_table(Square(s), bishop_attacks[s], bishop_masks[s],
                         bishop_magics[s], bishop_shifts[s], false);
        init_magic_table(Square(s), rook_attacks[s],   rook_masks[s],
                         rook_magics[s],   rook_shifts[s],   true);
    }
}

} // namespace Attacks
